[package]
name = "keyoverlay-rs"
description = "A simple key overlay for osu!"
version = "0.1.0"
authors = ["Miika Kurvinen <myuwi@proton.me>"]
license = "ISC"
edition = "2024"

[dependencies]
eframe = "0.32.3"
rdev = "0.5.3"
